sudo: false
language: node_js
node_js: stable
after_success:
  - |

        $(npm bin)/set-up-ssh --key "$encrypted_7bde748fd878_key" \
                             --iv "$encrypted_7bde748fd878_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"

        $(npm bin)/update-branch --commands "npm run build:posts" \
                                 --commit-message "Update website [skip ci]" \
                                 --directory "./public" \
                                 --distribution-branch "gh-pages" \
                                 --source-branch "master"
