sudo: false
language: node_js
node_js: stable
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
before_scripts:
- yarn run bootstrap
scripts:
- yarn test
after_success:
- |

  $(npm bin)/set-up-ssh --key "$encrypted_7bde748fd878_key" \
                       --iv "$encrypted_7bde748fd878_iv" \
                       --path-encrypted-key ".travis/github_deploy_key.enc"
  bash ./tools/push-to-github-io.sh
