sudo: false
language: node_js
node_js: stable
before_scripts:
- yarn run bootstrap
scripts:
- yarn test
after_success:
- |

  $(npm bin)/set-up-ssh --key "$encrypted_7bde748fd878_key" \
                       --iv "$encrypted_7bde748fd878_iv" \
                       --path-encrypted-key ".travis/github_deploy_key.enc"
